import = [ "./themes/dracula.toml" ]

[window]

opacity = 0.8

dimensions = { columns = 80, lines = 30 }

padding = { x = 20, y = 15 }

[font]

size = 14

normal = { family = "FiraCode Nerd Font", style="Regular" }
bold   = { family = "FiraCode Nerd Font", style="Bold" }
italic = { family = "FiraCode Nerd Font", style="Italic" }
bold_italic = { family = "FiraCode Nerd Font", style="Bold Italic" }
