import = [ "./themes/dracula.toml" ]

[window]

opacity = 0.8

dimensions = { columns = 120, lines = 60 }

padding = { x = 20, y = 15 }

[font]

size: 16

normal = { family = "FiraCode Nerd Font", style="Regular" }
bold   = { family = "FiraCode Nerd Font", style="Bold" }
italic = { family = "FiraCode Nerd Font", style="Italic" }
bold_italic = { family = "FiraCode Nerd Font", style="Bold Italic" }
